name: nextjs-task
services:
  postgres:
    image: postgres:15
    container_name: nextjs-task-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: postgres
    volumes:
      - nextjs-task-db-data:/var/lib/postgresql/data
      - ./build/local/docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  nextjs-app:
    build:
      context: ./users-app
      dockerfile: Dockerfile
    container_name: nextjs-task-app
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://postgres:${DB_PASSWORD:-postgres}@postgres:5432/postgres
      - NODE_ENV=production
    ports:
      - "3000:3000"

volumes:
  nextjs-task-db-data:
